ARG version="3"

FROM python:${version}-alpine

RUN apk update
RUN apk add make automake gcc g++ python3-dev

RUN pip install numpy pytest

WORKDIR /app
COPY example-app-1 .

CMD ["python", "app.py"]
